version: "3"
services:
  backend:
    container_name: ecolog_backend
    image: "ecolog_backend:0.1"
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - ecolog
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql
    container_name: ecolog_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - ./mysql/data:/var/lib/mysql
    cap_add:
      - SYS_NICE
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  redis:
    container_name: ecolog_redis
    image: redis:latest
    ports:
      - 6379:6379
    restart: always
    volumes:
      - ./redis/data/:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
networks:
  ecolog:
