version: "3"
services:
  backend:
    container_name: ecolog_backend
    image: "ecolog_backend:0.1"
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - ecolog
    environment:
      - TZ=Asia/Seoul
    restart: always
    networks:
      - ecolog_network 
  nginx:
    restart: always
    container_name: "ecolog_frontend"
    image: "ecolog_frontend:0.1"
    build:
      dockerfile: Dockerfile
      context: ./promotion
    ports:
      - "3000:80"
    networks:
      - ecolog_network
    environment:
      - TZ=Asia/Seoul
networks:
  ecolog_network:
