version: "3.7"
services:
  redis:
    container_name: ecolog_redis
    image: redis:latest
    ports:
      - 6379:6379
    restart: always
    volumes:
      - ./data/:/data
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    labels:
      - "name=redis"
      - "mode=standalone"
~